"""create prices table

Revision ID: 0d6b74cc8fd9
Revises: 
Create Date: 2026-03-15 00:57:44.364103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '0d6b74cc8fd9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('ts_unix', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("ticker in ('btc_usd', 'eth_usd')", name='ck_prices_ticker_allowed'),
    sa.CheckConstraint('price > 0', name='ck_prices_price_positive'),
    sa.CheckConstraint('ts_unix > 0', name='ck_prices_ts_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'ts_unix', name='uq_prices_ticker_ts')
    )
    op.create_index('ix_prices_ticker_ts', 'prices', ['ticker', 'ts_unix'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_prices_ticker_ts', table_name='prices')
    op.drop_table('prices')
    # ### end Alembic commands ###
